-- DEPRECATED — process-email-queue is now provisioned automatically.
--
-- This file used to be the *only* place the process-email-queue cron was
-- ever scheduled, and it required a human to paste a service-role key here
-- and run it by hand in the SQL Editor. Nothing re-asserted it, and nothing
-- would notice if it had never been run or had been dropped — which is the
-- root cause behind digest/report emails being enqueued successfully every
-- day but never actually delivered (see migration 20260816090000 for the
-- full writeup).
--
-- process-email-queue is now scheduled by:
--   - migration supabase/migrations/20260816090000_ensure_process_email_queue_cron.sql
--     (applied automatically by `supabase db push`)
--   - scripts/fix-email-crons.sql (re-asserted on every CI deploy, belt-and-suspenders)
--
-- Both reuse the already-provisioned `report_cron_service_role_key` vault
-- secret — no separate `email_queue_service_role_key` needed. If you ran an
-- older copy of this file that created `email_queue_service_role_key`, it's
-- harmless to leave in vault (or delete it); the cron job itself now always
-- points at `report_cron_service_role_key`.
--
-- Nothing to run here. Kept only so old bookmarks/history find an explanation
-- instead of a stale, silently-wrong setup script.
